name: React Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false

      # Deploy preview for pull requests
      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: preview/${{ github.event.pull_request.number }}
          publish_branch: gh-pages

      # Deploy production for master branch
      - name: Deploy Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages

      # Output deployment URLs in the action logs
      - name: Output Deployment URLs
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Preview URL (Your Changes): https://vimal-g-eq.github.io/testing-preview-url/preview/${{ github.event.pull_request.number }}"
            echo "Production URL (Current Master): https://vimal-g-eq.github.io/testing-preview-url"
          else
            echo "Production URL: https://vimal-g-eq.github.io/testing-preview-url"
          fi