name: React Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false

      # Deploy preview for pull requests
      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: preview/${{ github.event.pull_request.number }}
          publish_branch: gh-pages

      # Deploy production for master branch
      - name: Deploy Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages

      # Add comment to PR with URLs
      - name: Add PR Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const preview_url = `https://vimal-g-eq.github.io/testing-preview-url/preview/${context.issue.number}`;
            const production_url = 'https://vimal-g-eq.github.io/testing-preview-url';
            
            const comment = `## 🚀 Deployment URLs
            
            ### ✨ Preview (Your Changes)
            ${preview_url}
            
            ### 🌍 Production (Current Master)
            ${production_url}`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: comment
            });