name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages

      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: pr-preview/${{ github.event.pull_request.number }}
          publish_branch: gh-pages

      - name: Comment PR with Preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = `https://vimal-g-eq.github.io/testing-preview-url/pr-preview/${context.issue.number}/`
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: `🚀 Preview deployment is ready!\n\nPreview URL: ${previewUrl}`
            })

      - name: Output URLs
        run: |
          if [[ $GITHUB_EVENT_NAME == "push" ]]; then
            echo "Production deployment: https://vimal-g-eq.github.io/testing-preview-url/"
          elif [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            echo "Preview deployment: https://vimal-g-eq.github.io/testing-preview-url/pr-preview/${{ github.event.pull_request.number }}/"
          fi
