name: Preview Deployment

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  preview-deploy:
    uses: ./.github/workflows/setup-build-deploy.yml  # Make sure this path is correct
    with:
      node_version: '18'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-package-json:
    needs: preview-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update package.json for preview
        run: |
          json_file="package.json"
          preview_url="https://vimal-g-eq.github.io/testing-preview-url/preview/${{ github.event.pull_request.number }}"
          jq --arg url "$preview_url" '.homepage = $url' $json_file > tmp.json && mv tmp.json $json_file

  deploy-preview:
    needs: update-package-json
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: preview/${{ github.event.pull_request.number }}
          publish_branch: gh-pages

      - name: Output Preview URL
        run: |
          echo "Preview URL: https://vimal-g-eq.github.io/testing-preview-url/preview/${{ github.event.pull_request.number }}"
