# .github/workflows/preview-deploy.yml
name: Preview Deployment

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Add step to modify homepage for preview build
      - name: Update package.json for preview
        run: |
          json_file="package.json"
          preview_url="https://vimal-g-eq.github.io/testing-preview-url/preview/${{ github.event.pull_request.number }}"
          jq --arg url "$preview_url" '.homepage = $url' $json_file > tmp.json && mv tmp.json $json_file

      - name: Build
        run: npm run build
        env:
          CI: false
          PUBLIC_URL: "/testing-preview-url/preview/${{ github.event.pull_request.number }}"

      - name: Deploy Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: preview/${{ github.event.pull_request.number }}
          publish_branch: gh-pages

      - name: Output Preview URL
        run: |
          echo "Preview URL: https://vimal-g-eq.github.io/testing-preview-url/preview/${{ github.event.pull_request.number }}"