name: Production Deployment

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  production-deploy:
    uses: ./.github/workflows/setup-build-deploy.yml  # Make sure this path is correct
    with:
      node_version: '18'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-production:
    needs: production-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Production
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages

      - name: Output Production URL
        run: |
          echo "Production URL: https://vimal-g-eq.github.io/testing-preview-url"
