name: Setup and Build Deployment

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  setup-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false
